-- Seed data for authentication system
-- Created: 2025-11-13
-- Purpose: Create test users for development

-- Note: Passwords are hashed using bcrypt with 10 rounds
-- All test passwords are: "KaDong2024!"

-- Admin user
INSERT INTO users (
  email,
  password_hash,
  name,
  role,
  email_verified,
  preferences
) VALUES (
  'admin@kadong.com',
  '$2a$10$YourBcryptHashHere', -- Password: KaDong2024! (replace with actual hash)
  'Admin User',
  'admin',
  true,
  '{"theme": "light", "language": "vi"}'
);

-- Regular user
INSERT INTO users (
  email,
  password_hash,
  name,
  role,
  email_verified,
  preferences
) VALUES (
  'user@kadong.com',
  '$2a$10$YourBcryptHashHere', -- Password: KaDong2024! (replace with actual hash)
  'Test User',
  'user',
  true,
  '{"theme": "pastel", "language": "vi"}'
);

-- Guest user
INSERT INTO users (
  email,
  password_hash,
  name,
  role,
  email_verified,
  preferences
) VALUES (
  'guest@kadong.com',
  '$2a$10$YourBcryptHashHere', -- Password: KaDong2024! (replace with actual hash)
  'Guest User',
  'guest',
  false,
  '{}'
);

-- Note: Actual password hashes will be generated by the seed script using bcrypt
-- This is just a template. The actual implementation will use JavaScript to hash passwords.
